-- 코드를 입력하세요
# SELECT A.CART_ID FROM 
# (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') A,
# (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') B
# WHERE A.CART_ID = B.CART_ID

SELECT A.CART_ID
FROM CART_PRODUCTS A
LEFT JOIN CART_PRODUCTS B ON A.CART_ID = B.CART_ID
WHERE A.NAME = 'Milk' AND B.NAME = 'Yogurt'